services:
  vintago:
    container_name: backend
    networks:
      - backend-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
networks:
  backend-network:
    name: backend-network
    driver: bridge